<!-- Modal -->
<div class="modal fade" id="modalSeletBot" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="modalSeletBotLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalSeletBotLabel">Seleciona un bot</h5>
            </div>
            <div class="modal-body">
                <div class="row justify-content-center align-items-center g-2">
                    <div class="col-12">
                        <select class="form-select form-select-lg mb-3" aria-label=".form-select-lg" id="selectBotMain">
                            <option value="" selected>Selecionar un bot</option>
 
                        </select>
                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn bg-gradient-info" id="btn-select-bot-modal">Aceptar</button>
            </div>
        </div>
    </div>
</div>